### ISSUE TITLE
Local database persistence not working as expected

### ISSUE THREAD

**Issue by 0xdea** [RefactorSecurity/vscode-security-notes#4]
Based on my tests, the comments added to a project (either manually or via the Semgrep import feature) do not persist after the project is closed and reopened. I'm using Security Notes v1.0.0 local (JSON) database with VSCode 1.75.1 on macOS Ventura 13.2.1. Am I missing something?

**Comment by v8vito** [comment]
Hey @0xdea! Thanks for reporting this issue, we were able to reproduce the behavior. 

The underlying problem was the way we were handling relative paths for the local database file. Given that the default setting for the local persistence file was set to `.security-notes.json` (a relative path), persistence was not working as expected.

We'll be releasing a new version with the fix shortly.

Thanks again for your feedback!
