### ISSUE TITLE
Modifications do not impact the .security-notes.json file immediately

### ISSUE THREAD

**Issue by younrx** [RefactorSecurity/vscode-security-notes#7]
I would like to have an export tool, in order to generate a report listing every vulnerability found, and the associated file + line number. I don't know if you plan on including such a tool into your work (if you do, that would be amazing).

In the meantime I tried to used the .security-notes.json to generate such a report. The problem is that **the modifications I make are not saved into this file before I close vscode**... This means that I cannot generate this report right after doing a modification. I need to restart vscode to see the modifications that were made.

**Comment by ggabarrin** [comment]
Thanks for your feedback! 

Regarding the export feature, that is something we'd naturally want to add to the tool. For example, we'd be interested in supporting export formats such as CSV, HTML, and for tools such as Jira. We are planning on working on this feature once we clear a few known bugs.

As for saving the `.security-notes.json` file right after each change, we do want to implement this feature as well, but we'll need to consider the best strategy for tackling this. In the short term, we can implement a vscode command so that you can save the file on demand. Do you think that would be useful in the meantime? 

Thank you! :)

**Comment by younrx** [comment]
Thanks for the quick reply!

Glad to hear that you indeed plan to add this export feature. The possibility to manually save the file in the meantime would be a great help for sure ! Thanks for suggesting this temporary solution 👍

**Comment by ggabarrin** [comment]
Hey @younrx, we added a command for saving notes to the `.security-notes.json` file on demand. 

In order to use this command, please press `Ctrl+Shift+P` on Windows/Linux or `Cmd+Shift+P` on MacOS, type `Save Notes to Local Database`, and hit `Enter` :)

Thanks again for reporting this issue.

**Comment by younrx** [comment]
Thanks for the quick update! Can't wait to try it out 😉
